packaging_format = 2

id = "libretranslate"
name = "LibreTranslate"
description.en = "Open Source Machine Translation API, entirely self-hosted"
description.fr = "API de traduction automatique Open Source, entièrement auto-hébergée"

version = "1.3.0~ynh1"

maintainers = ["John doe"]

[upstream]
license = "AGPL-3.0"
website = "https://libretranslate.com/"
demo = "https://libretranslate.com/"
admindoc = "https://libretranslate.com/docs/"
code = "https://github.com/LibreTranslate/LibreTranslate"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/LibreTranslate/LibreTranslate/archive/refs/tags/v1.3.0.tar.gz"
        sha256 = "6f73d4d7d2e3b5a9bb0bb06877708d5b9101e7928fa15d82744ce0eca6af9773"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "libicu-dev, python3-venv, python3-icu, pkg-config, python3, python3-pip, python3-dev, build-essential, libssl-dev, libffi-dev, python3-setuptools"
